# 🐳 Docker Compose setup for the SampleByJoe Application
# This configuration builds and runs a simple React (frontend) and Node.js (backend)
# application as microservices, alongside a MongoDB database.
# All containers are networked together for seamless communication.

# docker-compose.yaml-version recommended: "3.8". 
# Note: Ensure Docker is installed and running on your machine to use this configuration.
# Uncomment the version line if you want to specify a version explicitly.
# NOTE: It has been commented out because Docker Compose v2 and above automatically detects file formart.
# version: "3.8"

services:

  # === Frontend Service ===
  samplebyjoe-client:
    image: munene97/samplebyjoe-client:v1.1.0
    build: ./client
    container_name: samplebyjoe-client
    stdin_open: true
    tty: true
    ports:
      - "3000:80" # Map port 80 in the container to port 3000 on the host
    depends_on:
      - samplebyjoe-backend
    networks:
      - samplebyjoe-net

  # === Backend Service ===
  samplebyjoe-backend:
    image: munene97/samplebyjoe-backend:v1.1.0
    build: ./backend
    container_name: samplebyjoe-backend
    stdin_open: true
    tty: true
    restart: always
    environment:
    - MONGODB_URI=mongodb://samplebyjoe-mongo:27017/yolomy # MongoDB connection string
    ports:
      - "5000:5000"
    depends_on:
      - samplebyjoe-mongo
    networks:
      - samplebyjoe-net

  # === MongoDB Database ===
  samplebyjoe-mongo:
    image: mongo
    container_name: app-mongo
    ports:
      - "27017:27017"
    networks:
      - samplebyjoe-net
    volumes:
     - type: volume
       source: app-mongo-data
       target: /data/db


# === Docker Network Configuration ===
networks:
  samplebyjoe-net:
    name: samplebyjoe-net
    driver: bridge
    attachable: true
    ipam:
      config:
        - subnet: 172.21.0.0/16
          ip_range: 172.21.0.0/16

# === Persistent Storage for MongoDB ===
volumes:
  app-mongo-data:
    driver: local
