---
- name: Deploy YOLO E-Commerce App
  hosts: all
  become: true
  
  roles: 
    - setup-mongodb
    - backend-deployment
    - frontend-deployment   

  vars:
    docker_network_name:
      name: samplebyjoe-net
      driver: bridge
      attachable: true
    docker_volume_name: 
      name: app-mongo-data