---
- name: Run MongoDB Container
  docker_container:
    name: app-mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - type: volume
        source: app-mongo-data
        target: /data/db
    networks:
      - name: app-net
    restart_policy: always
  tags:
    - database