---
- name: Pull the backend Docker Image
  docker_image:
    name: munene97/samplebyjoe-backend:v1.1.0
    source: pull

- name: Run Backend Container
  docker_container:
    name: samplebyjoe-backend
    image: munene97/samplebyjoe-backend:v1.1.0
    networks:
      - name: samplebyjoe-net
    ports:
      - "5000:5000"
    env:
      MONGO_URI_PRODUCTION: mongodb://app-mongo:27017/yolomy
      NODE_ENV: production
    restart_policy: always
  become: yes